spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: QuotingService
          uri: http://localhost:8082
          predicates:
            - Path=/api/quotes/**
            - Path=/api/devices/**
        - id: ReceivingService
          uri: http://localhost:8081
          predicates:
            - Path=/api/receive/**
        - id: CustomerService
          uri: http://localhost:8083
          predicates:
            - Path=/api/customer/**
